[tool.bumpversion]
current_version = "0.9.5.post1"
parse = """(?x)
    ^
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        (?P<pre_l>a|b|rc)
        (?P<pre_n>0|[1-9]\\d*)
    )?
    (?:
        (?P<dev>.dev)
        (?P<dev_n>0|[1-9]\\d*)
    )?
    (?:
        (?P<post>.post)
        (?P<post_n>0|[1-9]\\d*)
    )?
    $
"""
serialize = [
    "{major}.{minor}.{patch}{pre_l}{pre_n}",
    "{major}.{minor}.{patch}{dev}{dev_n}",
    "{major}.{minor}.{patch}{post}{post_n}",
    "{major}.{minor}.{patch}",
]
tag = false
tag_name = "v{new_version}"
commit = false
message = "Bump version: {current_version} â†’ {new_version}"

[tool.bumpversion.parts.pre_l]
values = ["a", "b", "rc"]
optional_value = "a"

[tool.bumpversion.parts.dev]
first_value = 1
independent = true

[tool.bumpversion.parts.dev_n]
first_value = 1

[tool.bumpversion.parts.post]
values = [".post"]

[tool.bumpversion.parts.post_n]

[[tool.bumpversion.files]]
filename = "tfism/version.py"
search = '__version__: str = "{current_version}"'
replace = '__version__: str = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "README.md"
search = "version-v{current_version}"
replace = "version-v{new_version}"

[[tool.bumpversion.files]]
filename = "README.md"
search = "compare/{current_version}...main"
replace = "compare/{new_version}...main"
